-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg8cYknYKyljbh7zrN
wNo3tB9aXrSTkUBRNWIlcKbWOOOgCgYIKoZIzj0DAQehRANCAARQZTVZvVI8mtTJ
8CwTjRDZ45jzf28GcxkzD+Jq44GNPHoPQwe4Fi7WUueQWXbMIkR/97/rtOPih/MI
zlMw1LMv
-----END PRIVATE KEY-----