//
//  ChatConstants.swift
//  RippleApp
//
//  Created by Mohd Aslam on 30/04/20.
//  Copyright © 2020 Fluper. All rights reserved.
//

import Foundation

struct cellidentifiers {
    static let SendertextCell       = "SendertextCell"
    static let Receivertextcell     = "Receivertextcell"
    static let SenderImageCell      = "SenderImageCell"
    static let ReceiverImageCell    = "ReceiverImageCell"
    static let SenderVideoCell      = "SenderVideoCell"
    static let ReceiverVideoCell    = "ReceiverVideoCell"
    static let SenderDocumentCell   = "SenderDocumentCell"
    static let ReceiverDocumentCell = "ReceiverDocumentCell"
    static let SenderLocationCell   = "SenderLocationCell"
    static let ReceiverLocationCell = "ReceiverLocationCell"
    static let SenderAudioCell      = "SenderAudioCell"
    static let ReceiverAudioCell    = "ReceiverAudioCell"
    static let MissedCallCell       = "MissedCallCell"
}

struct Parameters {
    static let UserSeenCount              = "UserSeenCount"
    static let CreatedBy                  = "group_id"
    static let Groups                     = "Groups"
    static let Message                    = "Messages"
    static let content                    = "message"
    static let videoName                  = "videoName"
    static let lastmessage                = "lastmessage"
    static let name                       = "name"
    static let senderid                   = "senderid"
    static let receiverid                 = "receiverid"
    static let message                    = "message"
    static let mediatype                  = "type"
    static let status                     = "status"
    static let img_type                   = "img_type"
    static let type                       = "type"
    static let mediaurl                   = "mediaurl"
    static let fileName                   = "fileName"
    static let mediaName                  = "mediaName"
    static let mediaSize                  = "mediaSize"
    static let unread_count               = "unread_count"
    static let groupName                  = "group_name"
    static let isDeleted                  = "deleted"
    static let blockUsers                 = "blockUsers"
    static let thumnilimageurl            = "video_thumbnail"
    static let ResentMessage              = "RecentMessage"
    static let UserState                  = "Users"
    static let readState                  = "readState"
    static let timeStamp                  = "timestamp"
    static let profile_image              = "profile_image"
    static let OnlineState                = "OnlineState"
    static let _id                        = "id"
    static let user_id                    = "_id"
    static let chat_id                    = "chat_id"
    static let alertmessage               = "Some Error node  not Found in Send data to firebase"
    static let Users                      = "members"
    static let information                = "information"
    static let emptyString                = ""
    static let saparaterString            = "_"
    static let nomessagesdata             = "No Data found"
    static let nobackupdata               = "No Backup Data found"
    static let location                   = "location"
    static let latitude                   = "latitude"
    static let longitude                  = "longitude"
    static let starmessage                = "starmessage"
    static let PrivateMessages            = "PrivateMessages"
    static let groupid                    = "group_id"
    static let  groupname                 = "group_name"
    static let admin_id                   = "admin_id"
    static let _friend                    = "_friend"
    static let sendername                 = "sendername"
    static let receivername               = "receivername"
    static let senderImage                = "senderImage"
    static let receiverImage              = "receiverImage"
    static let typingStat                 = "typingStat"
    static let Call                       = "Call"
    static let call_id                    = "call_id"
    static let isGroup                    = "isGroup"
    static let callType                   = "call_type"
    static let groupImage                 = "group_image"
    static let Members                    = "members"
    static let call_status                = "call_status"
    static let call_info                  = "call_Info"
}

struct CallIdentifiers {
    
    static let kChannelName               = "channelName"
    static let kReceiverTone              = "receiverTone"
    static let kCallerName                = "callerName"
    static let kCallerId                  = "callerId"
    static let kProfileImg                = "ProfileImg"
    static let kCallId                    = "call_id"
    static let bookingID                  = "booking_id"
}
